# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself

default_platform(:ios)

platform :ios do
  lane :build do
    gym
  end

  lane :beta do
    gym
    hockey(api_token: "abd77ea055c24f16877439deea9efbf1")
  end
end
